### ISSUE TITLE
auto label pull-requests

### ISSUE THREAD

**Issue by acud** [ethersphere/bee-runner#1]
having an automatic `pull-request` or `pr` label on every PR that we open in all the organization repos, this way we can have one dashboard in zenhub where we can see all outstanding pull requests on all repositories at once, therefore reducing time for reviews and increase sanitation of the repos in general.

**Comment by vandot** [comment]
@acud you mentioned also labeling issues with issue?

**Comment by acud** [comment]
i'm not sure we need it to be honest. we can add it i guess while you're at it if its not difficult.

**Comment by vandot** [comment]
Done, PRs labeled with `pull-request` and issues with `issue`

**Comment by acud** [comment]
awesome. thank you :pray:
